<?php
/**
 * Neon Database Connection Setup Script
 * This script helps you configure and test your Neon PostgreSQL connection
 */

echo "╔════════════════════════════════════════════════════════════════╗\n";
echo "║         Eat&Run - Neon Database Connection Setup              ║\n";
echo "╚════════════════════════════════════════════════════════════════╝\n\n";

// Check if running from command line
$is_cli = php_sapi_name() === 'cli';

if ($is_cli) {
    echo "=== NEON CONNECTION SETUP ===\n\n";
    
    // Check for command line arguments
    if ($argc > 1) {
        $action = $argv[1];
        
        if ($action === 'test') {
            testConnection();
        } elseif ($action === 'setup') {
            setupConnection();
        } elseif ($action === 'status') {
            checkStatus();
        } else {
            showHelp();
        }
    } else {
        showHelp();
    }
} else {
    // Web interface
    handleWebRequest();
}

function showHelp() {
    echo "Usage: php setup_neon_connection.php [command]\n\n";
    echo "Commands:\n";
    echo "  setup   - Interactive setup wizard\n";
    echo "  test    - Test current connection\n";
    echo "  status  - Check connection status\n";
    echo "  help    - Show this help message\n\n";
    echo "Example:\n";
    echo "  php setup_neon_connection.php test\n";
}

function setupConnection() {
    echo "=== INTERACTIVE SETUP WIZARD ===\n\n";
    
    // Get connection details from user
    echo "Enter your Neon connection details:\n\n";
    
    echo "Database Host (e.g., ec2-xx-xxx-xxx-xxx.compute-1.amazonaws.com): ";
    $host = trim(fgets(STDIN));
    
    echo "Database User (e.g., neondb_owner): ";
    $user = trim(fgets(STDIN));
    
    echo "Database Password: ";
    $password = trim(fgets(STDIN));
    
    echo "Database Name (e.g., neondb): ";
    $database = trim(fgets(STDIN));
    
    echo "Database Port (default 5432): ";
    $port = trim(fgets(STDIN)) ?: '5432';
    
    // Create .env file
    $env_content = <<<ENV
# Eat&Run Database Configuration
# Generated by setup_neon_connection.php

# PostgreSQL/Neon Configuration
DB_HOST=$host
DB_USER=$user
DB_PASS=$password
DB_NAME=$database
DB_PORT=$port

# Optional: Set to 1 if running on Render
RENDER=0

# Application Settings
APP_ENV=production
APP_DEBUG=0
ENV;
    
    // Write .env file
    if (file_put_contents('.env', $env_content)) {
        echo "\n✓ .env file created successfully\n";
        
        // Test connection
        echo "\nTesting connection...\n";
        testConnection();
    } else {
        echo "\n✗ Failed to create .env file\n";
        echo "Please ensure the directory is writable\n";
    }
}

function testConnection() {
    echo "\n=== TESTING DATABASE CONNECTION ===\n\n";
    
    // Load environment variables
    if (file_exists('.env')) {
        $env = parse_ini_file('.env');
        foreach ($env as $key => $value) {
            putenv("$key=$value");
        }
        echo "✓ Loaded .env file\n";
    } else {
        echo "⚠ .env file not found, using environment variables\n";
    }
    
    // Get connection details
    $host = getenv('DB_HOST') ?: 'localhost';
    $user = getenv('DB_USER') ?: 'root';
    $password = getenv('DB_PASS') ?: '';
    $database = getenv('DB_NAME') ?: 'food_ordering';
    $port = getenv('DB_PORT') ?: '5432';
    
    echo "\nConnection Details:\n";
    echo "  Host: $host\n";
    echo "  User: $user\n";
    echo "  Database: $database\n";
    echo "  Port: $port\n\n";
    
    // Test connection
    try {
        $dsn = "pgsql:host=$host;port=$port;dbname=$database;sslmode=require";
        $conn = new PDO($dsn, $user, $password, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_TIMEOUT => 5
        ]);
        
        echo "✓ Connected to database\n";
        
        // Test query
        $result = $conn->query("SELECT 1 as test");
        if ($result) {
            echo "✓ Query executed successfully\n";
            echo "✓ Database connection is working!\n\n";
            echo "✅ All tests passed!\n";
        } else {
            echo "✗ Query failed\n";
        }
        
    } catch (PDOException $e) {
        echo "✗ Connection failed: " . $e->getMessage() . "\n\n";
        echo "Troubleshooting tips:\n";
        echo "1. Verify host is correct\n";
        echo "2. Verify credentials are correct\n";
        echo "3. Ensure port is 5432\n";
        echo "4. Check if SSL is required (it is for Neon)\n";
        echo "5. Verify database exists\n";
    }
}

function checkStatus() {
    echo "\n=== CONNECTION STATUS ===\n\n";
    
    // Load environment variables
    if (file_exists('.env')) {
        $env = parse_ini_file('.env');
        foreach ($env as $key => $value) {
            putenv("$key=$value");
        }
    }
    
    $status = [
        'timestamp' => date('Y-m-d H:i:s'),
        'host' => getenv('DB_HOST') ?: 'Not set',
        'user' => getenv('DB_USER') ?: 'Not set',
        'database' => getenv('DB_NAME') ?: 'Not set',
        'port' => getenv('DB_PORT') ?: 'Not set',
        'env_file' => file_exists('.env') ? 'Present' : 'Missing',
        'connected' => false
    ];
    
    // Try to connect
    try {
        $host = getenv('DB_HOST');
        $user = getenv('DB_USER');
        $password = getenv('DB_PASS');
        $database = getenv('DB_NAME');
        $port = getenv('DB_PORT') ?: '5432';
        
        if ($host && $user && $database) {
            $dsn = "pgsql:host=$host;port=$port;dbname=$database;sslmode=require";
            $conn = new PDO($dsn, $user, $password, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_TIMEOUT => 5
            ]);
            $status['connected'] = true;
        }
    } catch (Exception $e) {
        $status['error'] = $e->getMessage();
    }
    
    // Display status
    foreach ($status as $key => $value) {
        if ($key === 'connected') {
            echo ($value ? '✓' : '✗') . " Connected: " . ($value ? 'Yes' : 'No') . "\n";
        } else {
            echo "  $key: $value\n";
        }
    }
}

function handleWebRequest() {
    // Web interface for testing
    ?>
    <!DOCTYPE html>
    <html>
    <head>
        <title>Neon Database Setup</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                max-width: 800px;
                margin: 50px auto;
                padding: 20px;
                background: #f5f5f5;
            }
            .container {
                background: white;
                padding: 30px;
                border-radius: 8px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }
            h1 {
                color: #333;
                border-bottom: 2px solid #006C3B;
                padding-bottom: 10px;
            }
            .form-group {
                margin-bottom: 15px;
            }
            label {
                display: block;
                margin-bottom: 5px;
                font-weight: bold;
                color: #333;
            }
            input {
                width: 100%;
                padding: 10px;
                border: 1px solid #ddd;
                border-radius: 4px;
                box-sizing: border-box;
                font-size: 14px;
            }
            button {
                background: #006C3B;
                color: white;
                padding: 10px 20px;
                border: none;
                border-radius: 4px;
                cursor: pointer;
                font-size: 14px;
                font-weight: bold;
            }
            button:hover {
                background: #005530;
            }
            .status {
                margin-top: 20px;
                padding: 15px;
                border-radius: 4px;
                display: none;
            }
            .status.success {
                background: #d4edda;
                color: #155724;
                border: 1px solid #c3e6cb;
                display: block;
            }
            .status.error {
                background: #f8d7da;
                color: #721c24;
                border: 1px solid #f5c6cb;
                display: block;
            }
            .info {
                background: #e7f3ff;
                border: 1px solid #b3d9ff;
                padding: 15px;
                border-radius: 4px;
                margin-bottom: 20px;
                color: #004085;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🗄️ Neon Database Connection Setup</h1>
            
            <div class="info">
                <strong>ℹ️ Info:</strong> Enter your Neon PostgreSQL connection details below to test the connection.
            </div>
            
            <form id="setupForm">
                <div class="form-group">
                    <label for="host">Database Host:</label>
                    <input type="text" id="host" name="host" placeholder="ec2-xx-xxx-xxx-xxx.compute-1.amazonaws.com" required>
                </div>
                
                <div class="form-group">
                    <label for="user">Database User:</label>
                    <input type="text" id="user" name="user" placeholder="neondb_owner" required>
                </div>
                
                <div class="form-group">
                    <label for="password">Database Password:</label>
                    <input type="password" id="password" name="password" required>
                </div>
                
                <div class="form-group">
                    <label for="database">Database Name:</label>
                    <input type="text" id="database" name="database" placeholder="neondb" required>
                </div>
                
                <div class="form-group">
                    <label for="port">Database Port:</label>
                    <input type="text" id="port" name="port" placeholder="5432" value="5432">
                </div>
                
                <button type="submit">Test Connection</button>
            </form>
            
            <div id="status" class="status"></div>
        </div>
        
        <script>
            document.getElementById('setupForm').addEventListener('submit', async (e) => {
                e.preventDefault();
                
                const statusDiv = document.getElementById('status');
                statusDiv.textContent = 'Testing connection...';
                statusDiv.className = 'status';
                
                const formData = new FormData(e.target);
                
                try {
                    const response = await fetch('test_db_connection.php', {
                        method: 'POST',
                        body: formData
                    });
                    
                    const result = await response.json();
                    
                    if (result.connected) {
                        statusDiv.textContent = '✓ Connection successful!';
                        statusDiv.className = 'status success';
                    } else {
                        statusDiv.textContent = '✗ Connection failed: ' + (result.error || 'Unknown error');
                        statusDiv.className = 'status error';
                    }
                } catch (error) {
                    statusDiv.textContent = '✗ Error: ' + error.message;
                    statusDiv.className = 'status error';
                }
            });
        </script>
    </body>
    </html>
    <?php
}
?>
